### ISSUE TITLE
https://pipes.toggl.com/ shows white page in browser

### ISSUE THREAD

**Issue by webervin** [toggl/pipes-ui#8]
ping @syko

**Comment by leafi** [comment]
![2016-05-26-230118_1031x569_scrot](https://cloud.githubusercontent.com/assets/2166555/15591546/a8c380b8-2395-11e6-8f95-7e46a74b7861.png)

**Comment by syko** [comment]
pipes.toggl.com has an old version deployed.
I pushed a new tag so HEAD is now an official release. I can't deploy however since the production server seems to be different from what it was a year ago.

**Comment by webervin** [comment]
Criteria for closing issue: pipes.toggl.com does not show white square instead of page

**Comment by webervin** [comment]
works better.
